version: '3'
services:
  master:
    build:
      context: ./master
    image: jenkins/master
    environment:
      JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins-home-master:/var/jenkins_home
  node:
    build:
      context: ./node
    image: jenkins/node
volumes:
  jenkins-home-master:
    driver: local
